export const FETCH_ADTL_COMPLAINTS_START = "FETCH_ADTL_COMPLAINTS_START"; 
export const FETCH_ADTL_COMPLAINTS_SUCCESS = "FETCH_ADTL_COMPLAINTS_SUCCESS"; 
export const FETCH_ADTL_COMPLAINTS_FAIL = "FETCH_ADTL_COMPLAINTS_FAIL"; 